### ISSUE TITLE
JBSCI

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/event#15]
https://www.figma.com/file/VDSBqsGIrpIGE09GccNefK/JBSCI?type=design&node-id=0%3A1&mode=design&t=3tz9NNf64vNyS8g8-1

其它见群

**Comment by iRuxu** [comment]
## 路由问题
![ecb7c6cd1c12c6fb6b0948890a07280a](https://github.com/JX3BOX/event/assets/8476969/4532ec89-f966-48f0-930c-af564713a5b2)

- [x] 已完成

**Comment by iRuxu** [comment]
## 模块内容筛选
<img width="1716" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/671f6cd0-642c-485b-ae41-b85360ad69bc">

- [x] 已完成

**Comment by iRuxu** [comment]
## 头像问题

<img width="981" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/299a9c26-6f45-42ad-81ba-12bd15889ea8">

- [x] 已完成

**Comment by iRuxu** [comment]
## 搜索优化

<img width="1718" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/86f4a8c5-9789-4b64-941b-c49efd570ed7">

- [x] 已完成

**Comment by iRuxu** [comment]
## 后台

<img width="1700" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/dc3a4492-d4c0-4fa1-8224-26f9a02da247">

- [x] 已完成

**Comment by iRuxu** [comment]
## 顺序
<img width="459" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/4b44150c-97a7-4b72-bf86-283598542051">

- [x] 已完成

**Comment by iRuxu** [comment]
## 作品
<img width="1028" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/a49dc83d-a690-4a44-946e-999a723aa2a5">

- [x] 已完成

**Comment by iRuxu** [comment]
## 图片
<img width="430" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/001cba08-86cc-4792-bfb6-ffb148305f59">


- [x] 已完成 

------
现在的图就是胧月打包发给我的

------
那等他再发个新版给你

**Comment by iRuxu** [comment]
## 导航
<img width="733" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/645d0df0-7c2f-43ce-bae7-bde5c6200a76">
等胧月给图

- [ ] 已完成

**Comment by iRuxu** [comment]
## 季度banner

<img width="849" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/4aa8ce1b-3676-434c-9754-d601130d9800">

- [x] 已完成

**Comment by nierssaxa** [comment]
### 首页
![image](https://github.com/JX3BOX/event/assets/97571785/e30f44a1-7d52-480a-875f-108efda21976)
不要做入场动画（从下到上渐入的那个），让文字直接展示

PS，最好做一个缓存，用户已经看过一次这个动画后，下次来主页，都不会再看到这一幕（除非ctrl+F5），类似于我们的贺卡功能。

- [x] 已完成

**Comment by nierssaxa** [comment]
### 首页底部
![image](https://github.com/JX3BOX/event/assets/97571785/03f47c2f-57b9-4c5c-b6f4-5b6f7607a1e6)
给这一块画一个固定高度69px的区域，让其固定在浏览器的底部，尽量避免不出现这样下面过多的留白

- [x] 已完成

**Comment by nierssaxa** [comment]
### slider自适应
![185cca5d96c0257224b90dce4f7acd32](https://github.com/JX3BOX/event/assets/97571785/06d6168f-61ad-41ca-95c1-0e0260a32953)
先按照上一条，整个页面【顶部魔盒菜单】【JBSCI文字】【JBSCI logo】【标签页】【底部的about jbsci】这些都是固定高度，宽度自适应。
然后slider直接填充剩余部分，如图slider应该高度拓展到箭头指引部分。
slider内部的图片直接等比放大即可

- [x] 已完成

**Comment by nierssaxa** [comment]
### 首页
![image](https://github.com/JX3BOX/event/assets/97571785/e1017df9-a0b9-48cb-b0c3-128cb29b70dc)
中文改成13px

- [x] 已完成

**Comment by nierssaxa** [comment]
### 作品
![8d21e3a57bad2c5ca7ab8af2e256682c](https://github.com/JX3BOX/event/assets/97571785/0f74f1b2-11c6-4f98-99bd-00d9652baa16)

按照浮烟的要求，每1季度都会有一个季度banner
季度banner上面要有一个分割线
同时每次季度之间的间距要变成40px
如图（figma）

- [x] 已完成

**Comment by iRuxu** [comment]
## 年份排序
<img width="803" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/31ac32af-aef8-4bd8-b525-d22388e6441c">

- [x] 已完成

**Comment by iRuxu** [comment]
## 刷新访问
![693339a50e4715ecf28739e77bd2bd9c](https://github.com/JX3BOX/event/assets/8476969/fd7e894a-67f6-4c97-87bd-5fc401ae7352)

选择某个tab，刷新访问怎么又要slider。
这个黑屏slider是一次的，做个localstorage记录吧 

`event_jbsci_cover`

另外如果带个路由进来，就直接进去，不要再进黑屏。
包括banner屏应该是index，带了也不进黑屏

- [x] 已完成

**Comment by nierssaxa** [comment]
### 作品封面

![image](https://github.com/JX3BOX/event/assets/97571785/2aedb16a-7718-49a1-8716-402e739285e8)
这个代码写在图上得字调整成24px

- [x] 已完成

**Comment by nierssaxa** [comment]
### 作品
![ca4cc82fa117f91919d55878659f6611](https://github.com/JX3BOX/event/assets/97571785/43229ae8-b834-4309-84d0-6bf3e8ca9b31)
1.调整成20 x 20px
2.字体改为12px
3.字体改为12px

![image](https://github.com/JX3BOX/event/assets/97571785/cb6561ad-2f65-4057-821a-ea26ccfe2d1d)

- [x] 已完成

**Comment by nierssaxa** [comment]
### 作者
![9dc8132230506f9f4efd1d798311e93c](https://github.com/JX3BOX/event/assets/97571785/8a1b1618-85a9-491d-936d-244be40fb918)

1. 加入魔盒四个字 改成 Join in ，时间放到后面，例：【Join in 2020-02-04】
2. 字体改成12px
3. 字体改成12px

![image](https://github.com/JX3BOX/event/assets/97571785/39fbb1c9-6bdc-47ea-bafb-2cf391c31579)

- [x] 已完成

**Comment by iRuxu** [comment]
![933abe96d645e16f04d7038e7a460a24](https://github.com/JX3BOX/event/assets/8476969/a9ba0ef1-2ad1-4e50-a4de-9f6264031b0a)

（1）中文标题，12个字以内，不要用【】这样的标记，高度概括重点
（2）封面英文，前端通过"|"竖杠字符自动换行，最多只能2行，英文长度自己看上面的demo。
（3）英文点评，不超过5行。可以是文章的优劣，也可以是比如 30万点赞等这样的言语。

![79cddb635c917f04ca3280e93df2258c](https://github.com/JX3BOX/event/assets/8476969/4277297c-0dd1-4d54-b4ce-119631e92560)

![153491cf11a219f44513e7605c65256c](https://github.com/JX3BOX/event/assets/8476969/dcac75c5-1897-4a84-9231-bb15d88ac3fa)

![aa2b0b3b4dc1ddef58616eb287c48dd2](https://github.com/JX3BOX/event/assets/8476969/72879032-6bf8-48a9-a5a8-7dad9a92845f)

- [ ] 已完成
