### ISSUE TITLE
JBSCI

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/event#16]
## 关于部分

<img width="626" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/1c36f732-8e80-4aba-beda-8b6a09defb34">

这里调用公告，不要本地写死

<img width="1707" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/7149a145-aeff-4a29-ba64-8bef09ad544c">

- [x] 已完成

**Comment by iRuxu** [comment]
## 导航
<img width="733" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/645d0df0-7c2f-43ce-bae7-bde5c6200a76">

胧月不是说弄完了吗

- [x] 已完成

**Comment by iRuxu** [comment]
## 链接

因为我们有正式服+怀旧服
写链接不要用写__Root

固定 / 开头，自动就从当前域名的根开始了啊。

后台录的作品地址不要 bps/123 要写成  /bps/123


- [x] 已完成  后台要改比较麻烦，前端已加 /

**Comment by nierssaxa** [comment]
### logo
完整的logo是由4个vector组成的，目前来看线上的只有其中一个
1. 检查一下从figma导出的名字 （Vector错的，#ba9624ff错的，Logo对的）
2. 正确的logo文件已经在1月4号上传到群文件，JBSCI.zip里
3. 用logo.svg的情况下，size是 80x80，上下距离10px
4. 4天前localhost下的logo看上去是对的（[详见](https://github.com/JX3BOX/event/issues/15#issuecomment-1879676991)）
### 当前线上
![image](https://github.com/JX3BOX/event/assets/97571785/ba861d78-fd16-42d5-b241-942ccdf3d594)
### 应当布局
![3dc6d97b6fc1f9b3cdcafcda9c8b563d](https://github.com/JX3BOX/event/assets/97571785/2211f9c0-efe3-42e2-9989-d4d5eb698231)
### svg
![Logo](https://github.com/JX3BOX/event/assets/97571785/44df55ec-497b-4686-be40-19eb7e83672a)


- [x] 已完成

**Comment by iRuxu** [comment]
## 学会用css断行

<img width="706" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/c5b72a5f-8583-406d-8a32-1253250792b6">

后台录入，如非必要，不需要搞html，除了颜色高亮那些
其它的，直接通过回车就可以

回车后会生成`\n`的换行符

通过css的`white-space:pre-line`即可实现换行效果。
自己看下MDN：https://developer.mozilla.org/zh-CN/docs/Web/CSS/white-space

- [x] 已记住

**Comment by iRuxu** [comment]
## 仅开发模式不缓存

<img width="1013" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/d65d43ca-2371-4cfd-8da8-083e61957ee2">

<img width="886" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/ea06e9b1-290f-48b5-88dd-32dfc322651a">

构建工具在构建或本地跑服务的时候，会在进程里有个环境变量
只有开发环境才不启用缓存，平时肯定要缓存啊

- [x] 已记住
