### ISSUE TITLE
新版高考专题

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/event#2]
https://www.figma.com/file/qiO3V6aCLEAX3lCYbDoBZA/Untitled?type=design&node-id=0%3A3&t=yHxFBg0tnCVcMSi3-1

**Comment by iRuxu** [comment]
<img width="606" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/3799824e-cc69-4b77-b9c0-32e792370c3e">

这里面不要乱动啊，很奇怪

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1368" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/0bf33eac-0cb5-438a-a778-b230ec99d93e">

背景应该整体就是这个紫色

- [x] 已完成

**Comment by iRuxu** [comment]
配置的灵活性说明

默认我们这个地址估计就叫 /gaokao

然后通过?year=2023来指定。

比如，你本地assets/data里有个json来配置

2023年就是固定的6要试卷，你存好id

然后访问2023的时候，那么就请求这6套试卷来渲染上面的tab

请求对应的试卷id加载内容

这样才能做到实时变化

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="278" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/75b6cf64-4b23-4308-b227-64466cc01db4">

这个2023的z字，弄成代码写，这样请求哪一年，就显示多少。

然后如果不是在json里面的，也就是比如乱写year=2077那么就不存在的就总是调用2023，相当于2023是默认值

明年如果要换皮肤，就在使用顶层div换class去弄

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1452" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/13d39a56-b723-4983-a2cd-d26db4873a5a">

这个颜色，改成和背景主题紫色一致

- [x] 已完成

**Comment by nierssaxa** [comment]
预先加载6(7)张卷子，将其平铺，在平面上。
通过右侧导航栏切换卷子，切换卷子时应当加入一个卷子向左移动的动画。
正在使用的卷子为100%透明。左右两侧未使用的卷子50%透明且不展示题目。
每个卷子有自己的配色。
具体看figma。
注意，第一个卷子左侧应当是最后一个卷子，最后一个卷子右侧应当是第一个卷子。

**Comment by iRuxu** [comment]
## 待优化项

1. 无法通过一个链接进入到某个试卷。
?year=2023&paper=$paperID
点击切换的时候也replace route

2. 每一个选项的hover和Active颜色使用主题色，没有才默认色
<img width="969" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/0a9b6f6c-0a9f-43d2-bb81-fb34f52ee4a7">

- [x] 已完成
