### ISSUE TITLE
诗词接口更换

### ISSUE THREAD

**Issue by Kaviilee** [JX3BOX/event#20]
## 列表
![QQ_1725891506898](https://github.com/user-attachments/assets/a23a9c78-1046-4cd0-a67e-8afbfab040c2)

### next2 接口
![QQ_1725891696477](https://github.com/user-attachments/assets/4f45d82d-c003-4ac6-a047-f7e905d53a48)

![QQ_1725891805422](https://github.com/user-attachments/assets/beb52141-3ee2-4299-a7fa-2715d72709da)

- [x] 已完成

**Comment by Kaviilee** [comment]
## 小程序一样

- [x] 已完成

**Comment by iRuxu** [comment]
## 随机展示

诗词的列表，请随机排序，不要固定排序
前端做随机

- [x] 已完成
