### ISSUE TITLE
抽奖一期验收

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/event#9]
## 2x资源替换
<img width="1904" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/3a16214a-e93b-40cc-9428-047e964294ca">

- [x] 已完成

**Comment by iRuxu** [comment]
## 文字配置
<img width="750" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/0e3be28f-3dc6-4d6f-93f8-5112b528614e">

- [x] 已完成

**Comment by iRuxu** [comment]
## 随机开盒

随机开盒应该是一个东西吧，现在似乎也显示了多个东西？

- [x] 已完成

**Comment by iRuxu** [comment]
## 后台与前端逻辑验收
<img width="1914" alt="image" src="https://github.com/JX3BOX/event/assets/8476969/70b184c0-095e-4f04-94cf-d0345a5a1acf">
https://swagger.jx3box.com/swagger.html?urls.primaryName=pay.jx3box.com

此项由醉栩完成

- [ ] 已完成

**Comment by Kaviilee** [comment]
## 前端验收

1. 很奇怪的逻辑，你直接让用户进来的时候登录不就行了，为啥要加mask层
![image](https://github.com/JX3BOX/event/assets/25825282/adb3601c-337d-44db-a200-e3c4e5b27cc9)
- [x] 已完成

2. 积分没有实时变化，奖品一栏字体存在问题
![image](https://github.com/JX3BOX/event/assets/25825282/1e0cac41-e9b1-4bf8-b146-4f5c1c3203bf)

- [x] 已完成

2. 图片裂的
![image](https://github.com/JX3BOX/event/assets/25825282/2ebf5b8e-cb32-4ed5-9654-d14235d1374c)

- [x] 已完成

3. 有个小建议，奖品跳转到具体详情会不会好一点？（好不好实现
![image](https://github.com/JX3BOX/event/assets/25825282/de6384c3-9a4a-4a99-a54e-65c1453edb10)

- [x] 已完成

4. 查看详情怎么还是拿下
![image](https://github.com/JX3BOX/event/assets/25825282/f14a7b67-0bc0-4998-ada2-5ce8332d9cb0)

- [x] 已完成

5. 当我全部打开时，历史记录无法打开
![image](https://github.com/JX3BOX/event/assets/25825282/20c0b487-f3ac-4d9e-9596-61f8309f02bc)

- [x] 已完成

6. 快速点击随机抽取的问题依旧存在，应该使用debounce而不是throttle

**Comment by Kaviilee** [comment]
## 后台
1.
![image](https://github.com/JX3BOX/event/assets/25825282/9b97e17c-6fcc-4f3c-b359-7a2e978a78f0)

- [x] 已完成

2.
![image](https://github.com/JX3BOX/event/assets/25825282/c222d33d-248f-4020-93f5-99061c29c76d)

- [x] 已完成
3.
<img width="757" alt="975642aee6e1b84bd8da5b14cb063717" src="https://github.com/JX3BOX/event/assets/25825282/059afa82-2a28-4ce7-bb5c-681c6a5038c4">
<img width="466" alt="70877ad0294153ab5c9d294d31773206" src="https://github.com/JX3BOX/event/assets/25825282/54e72f8e-328d-44ea-9494-eca6c3922a1a">
对不上？

- [x] 已完成

4. 
![image](https://github.com/JX3BOX/event/assets/25825282/05839915-720c-4295-8a14-136bf5d37694)

- [x] 已完成
